#!/usr/bin/env bash
set -euo pipefail

# Generate compose.override.yml for local repo mounts.
# This file is .gitignored and regenerated on demand.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

OVERRIDE_FILE="$ROOT_DIR/compose.override.yml"

cat > "$OVERRIDE_FILE" << 'EOF'
# Auto-generated by dev/scripts/setup-dev.sh
# Local repo mount overrides for development mode.
#
# Add volume mounts for local submodule development:
#
# services:
#   <service>:
#     volumes:
#       - ./repos/<package>:/app/node_modules/<package>:ro

services: {}
EOF

echo "Generated $OVERRIDE_FILE"
